### ISSUE TITLE
 User can see a list of Features for the top 5 cheapest game in the home page

### ISSUE THREAD

**Issue by pissypheous** [sal-garcia/ajax-project-updated#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to see the 5 cheapest game available in all of those stores
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive app that allows users to sees images and data from an api
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (173)](https://user-images.githubusercontent.com/51901536/153692744-abd99127-8a76-46a5-aa91-faeb6b8bb338.png)
## ✅ Task List

![Screenshot (177)](https://user-images.githubusercontent.com/51901536/153694201-1197ea55-3fce-42a4-94fd-1810fef0d433.png)

> ##### Commit checklist for tasks needed to complete the feature.

 

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] use html and css to create the skeleton and decorate it
- [x] decorate the home page that displays the 5 cheapest games
- [x] make sure you use the cheapshark to pull data from the api's
- [x] make sure the links in the nav bar are working
- [x] make sure the search bar in the nav bar works
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
