### ISSUE TITLE
Feature: User can compare the prices of games between different websites

### ISSUE THREAD

**Issue by pissypheous** [sal-garcia/ajax-project-updated#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to compare prices of games between 3 different websites
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be able to type a game title on a search bar and compare prices
## 🖼️ Wireframes
![Screenshot 2022-03-07 001709 (3)](https://user-images.githubusercontent.com/51901536/156994880-abce3070-9274-4343-b7b2-95e1c63548d7.png)
![Screenshot 2022-03-07 003512](https://user-images.githubusercontent.com/51901536/156998316-6801cb93-36c4-4623-9c1d-cc30485b5acb.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make sure that the search bar works
- [x] make sure that the search button works

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
