### ISSUE TITLE
Feature: User can search for game

### ISSUE THREAD

**Issue by pissypheous** [sal-garcia/ajax-project-updated#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to search a game by name on the search bar
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be able to click search on the search bar in order to search for that game
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (7)](https://user-images.githubusercontent.com/51901536/162354453-873920a0-8e95-43c8-aff5-f5f16e167d0d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
 
- [x] make sure that the games are displayed in the body of the page after the search is done

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
