### ISSUE TITLE
user can get alerts when a game drops in price

### ISSUE THREAD

**Issue by pissypheous** [sal-garcia/ajax-project-updated#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can save the old price of the game and check if the lowest price has changed later when he comes back

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
user will receive an email when the price of a game is lowered

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![web last](https://user-images.githubusercontent.com/51901536/165233531-11242bb0-e433-4b48-a572-819ad5adf881.png)

![phone last](https://user-images.githubusercontent.com/51901536/165233547-0070908a-985f-444c-86fa-02d94d5799f8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make sure that there is also a form on the bottom incase you want to sign up for price drop notifications
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
