### ISSUE TITLE
user can view information on the stores that are being compared

### ISSUE THREAD

**Issue by pissypheous** [sal-garcia/ajax-project-updated#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can view information of the websites that sell the game
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be able to click a link and view the logo of each store along with the name of each store
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![phone issue 5](https://user-images.githubusercontent.com/51901536/164610011-b8f8bc93-be5b-4f30-a043-90dc3aa8beba.png)

![issue 5 no 1](https://user-images.githubusercontent.com/51901536/164609702-8f832a7f-cd77-400f-b817-d6df6adb6df3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] make sure that the store info link hides everything thats not related to the store
- [x] make sure that the link shows images and a paragraph relating to the stores
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
